# 启动端口号
server:
  post: 8000
# MySQL数据源配置
mysql:
  username: root
  password: root
  url: tcp(0.0.0.0:3306)/mall_db?charset=utf8&parseTime=True&loc=Local

# JWT配置
jwt:
  signingKey: z3d6k8v0n3w7m9sa1fd0u09h

# 七牛配置
qiniu:
  AccessKey: tCoZnAbWbRBy--yZuDnA-ZdUdXL20YXeNBtoiJrW
  SerectKey: GdMqlREmJuQ4Fo-xlHnbTO8G6yqsrvP4EBTHU-p3
  # Bucket = 
  # QiniuServer = 
email:
  ValidEmail: http://localhost:8080/#/vaild/email/
  SmtpHost: smtp.qq.com
  SmtpEmail: 2605791375@qq.com
  SmtpPass: tccsmobljsgyecei

es:
  EsHost: 127.0.0.1
  EsPort: 9200
  EsIndex: mylog
redis:
  RedisDb: redis
  RedisAddr: 127.0.0.1:6379
  RedisPw:
  RedisDbName: 2